# Optional : will write cookies as JSON file once successfully logged in, then
# reuse it on subsequent runs. If specified, this URL will be visited before
# any other page to be tested on first run.
# TODO switch based on a per-page opt-in or opt-out basis (logged in and logged
# out) in the same run ?
login:
  user: hello # Optional. Fallback to process.env.LOGIN_USER
  pass: helloPassword # Optional. Fallback to process.env.LOGIN_PASS
  url: https://example.com/login
  userInputSelector: '#email'
  passInputSelector: '#password'
  rememberMeInputSelector: 'input[name="rememberMe"]'
  submitSelector: 'button[type="submit"]'
  # This allows to interact with the page at different moments (like events).
  hooks:
    # The "before" event is called before entering the values in the login form
    # input fields. By default, all selectors defined above are already "waited
    # for".
    # before:
    # The "after" event is called after submitting the login form. It allows to
    # deal with asynchronous form submissions (without page navigation),
    # ensuring we don't attempt to write cookies too early.
    after:
      waitForSelector: 'header.MuiAppBar-root .MuiIconButton-label > .MuiBadge-root'

input:
  homepage:
    url: https://example.com
  list:
    url: https://example.com/list
  entry:
    url: https://example.com/entry

# Keep screenshots along with measures.
output:
  screenshot: true
